language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install selenium sauceclient requests robotframework robotframework-ride robotframework-selenium2library"
# command to run tests
script: export PATH=$PATH:pwd & pybot TestTravis.txt
addons:
  sauce_connect:
    username: "qazp"
    access_key: "7a182ce9-a60c-4e08-b1c4-88123f2511fd"