language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -U pytest selenium sauceclient requests robotframework robotframework-ride robotframework-selenium2library"
# command to run tests
script: export PATH=$PATH:.:/home/travis/virtualenv/python2.7.9/ && echo $PATH && cd /home/travis/build/swissfiscal/testabc/ &&sleep 5&& dir && pybot TestTravis.txt
addons:
  sauce_connect:
    username: "qazp"
    access_key: "7a182ce9-a60c-4e08-b1c4-88123f2511fd"