language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install selenium sauceclient requests robotframework robotframework-ride robotframework-selenium2library"
# command to run tests
script: python pyunitttest.py
addons:
  sauce_connect:
    username: "Your Sauce Labs username"
    access_key: "Your Sauce Labs access key"